API_ID: 18543259
API_HASH: 491ca8ad95823d9d1c428b77a3bd27f7
BOT_TOKEN: 5691516512:AAFzijV89HH0wEq0hlM6J4-9i0Tm7h61OTU


MONGO_URL: mongodb+srv://diez:WswvMh9lAUfMk5lN@cluster0.3ngmld1.mongodb.net/?retryWrites=true&w=majority
REDIS_URI: redis-14837.c278.us-east-1-4.ec2.cloud.redislabs.com
REDIS_PORT: 14837
REDIS_PASS: nSyGUWjFGFUUDRIPWqdGpCwLsjX5BBt6

SESSION_API_ID: 18543259
SESSION_API_HASH: 491ca8ad95823d9d1c428b77a3bd27f7
SESSION_STRING: 1ApWapzMBu5iFOiKJpeFMdC8KIpdL-n1vrBFTlIp65crTtLQfwR4v5a2CGBZawyGw5qfeYD1IBKwnVfpXK5dQvg1yJuXhN7ajgviXceSPgQsSUnoijOKikvQmmOa-2hmOMKgbRSpYN5T4jiyrNTfmBbf6yaNSdfWbZG7vuiVA2HHvUBvaqZT-bTUKVXL2MUnmS8YW2gs3Qe3s9tkuiWA5nCJ5mn2mJJQSQAnq_xb4-W5tR4OhF94d9dtEV_Jz4yY9s6iQK1zOo0qebLsu0h0zXps7YnenFrMaEuP17eOQ0WzhD3RgzEfgvNZA9xDmZO1SmUn6uxhqJaytsyGEeVPTzx4qdTQfQWM=

ADMINS:
  - 5106097171

OWNER: 5106097171

BOT_PIC: https://te.legra.ph/file/a44cc6ec55eeafec0c558.jpg
OWNER_PIC: https://te.legra.ph/file/280c6f1a2fbf10caf0822.jpg


SUPPORT_CHAT: logs 
# LOG_CHAT: 
LOG_CHAT: -829052674



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

